# -*- coding: utf-8 -*-
"""SlideForge 主题库 —— 24 种设计风格（类型）+ 24 个用途分类。

仅包含版式与占位示例文本，不含任何正式业务内容。
"""
FONT_SANS = "Segoe UI"
FONT_SANS_EA = "微软雅黑"
FONT_SERIF = "Georgia"
FONT_SERIF_EA = "宋体"
FONT_MONO = "Consolas"
FONT_MONO_EA = "等线"

# 幻灯片切换动效（注入 <p:transition>）
THEMES = {
    "build": dict(label="呼吸留白极简", en="Breathing Whitespace", preset="11 Build",
        philosophy="大量留白 + 单一强调色，克制中性，便于替换成任意品牌色。",
        bg="FBFBFA", surface="FFFFFF", ink="1A1A1A", ink2="8A8A8A", accent="2F6BFF", accent2="1A1A1A",
        line="E6E6E6", title_font=(FONT_SANS, FONT_SANS_EA), body_font=(FONT_SANS, FONT_SANS_EA),
        radius=0.10, decor="min", transition="fade"),
    "brockmann": dict(label="数学网格功能主义", en="Swiss Grid", preset="10 Müller-Brockmann",
        philosophy="严格网格与对齐，双色体系，适合数据、计划与结构化汇报。",
        bg="FFFFFF", surface="F7F7F5", ink="111111", ink2="6B6B6B", accent="E2231A", accent2="111111",
        line="D8D8D4", title_font=(FONT_SANS, FONT_SANS_EA), body_font=(FONT_SANS, FONT_SANS_EA),
        radius=0.0, decor="grid", transition="push"),
    "takram": dict(label="柔和科技图表", en="Soft Tech", preset="17 Takram",
        philosophy="圆角、柔影与图表即艺术，适合作品集、产品提案与数据看板。",
        bg="F5F3EF", surface="FFFFFF", ink="2B2B2B", ink2="9A9A93", accent="3FA88C", accent2="E2A03F",
        line="E4E0D8", title_font=(FONT_SANS, FONT_SANS_EA), body_font=(FONT_SANS, FONT_SANS_EA),
        radius=0.24, decor="soft", transition="fade"),
    "corporate": dict(label="商务蓝调", en="Corporate Blue", preset="09 Experimental Jetset",
        philosophy="沉稳海军蓝 + 金色点缀，适合汇报、方案与数据看板。",
        bg="FFFFFF", surface="F2F5FA", ink="10233F", ink2="5B6B82", accent="1E5FBF", accent2="C9A227",
        line="D7E0EE", title_font=(FONT_SANS, FONT_SANS_EA), body_font=(FONT_SANS, FONT_SANS_EA),
        radius=0.06, decor="band", transition="wipe"),
    "darkneon": dict(label="暗黑霓虹", en="Dark Neon", preset="06 Active Theory",
        philosophy="深空底色 + 霓虹青/品红，适合游戏提案、发布与科技主题。",
        bg="0B0F1A", surface="151B2B", ink="EAF2FF", ink2="94A3C4", accent="22D3EE", accent2="F472B6",
        line="26314B", title_font=(FONT_SANS, FONT_SANS_EA), body_font=(FONT_SANS, FONT_SANS_EA),
        radius=0.08, decor="glow", transition="morph"),
    "retropixel": dict(label="复古像素", en="Retro Pixel", preset="16 Territory Studio",
        philosophy="暗紫底 + 糖果色块，呼应像素美术与独立游戏审美。",
        bg="1B1B2F", surface="262647", ink="F4F4F8", ink2="A6A6C9", accent="FF6B6B", accent2="FFD93D",
        line="3B3B63", title_font=(FONT_MONO, FONT_MONO_EA), body_font=(FONT_SANS, FONT_SANS_EA),
        radius=0.0, decor="pixel", transition="push"),
    "editorial": dict(label="杂志编辑", en="Editorial", preset="19 Irma Boom",
        philosophy="暖纸底 + 砖红点缀，衬线标题，适合作品集与深度叙事。",
        bg="FAF6F0", surface="FFFFFF", ink="1C1B19", ink2="7A756C", accent="B23A2E", accent2="2A2A28",
        line="E7DFD2", title_font=(FONT_SERIF, FONT_SERIF_EA), body_font=(FONT_SANS, FONT_SANS_EA),
        radius=0.0, decor="rule", transition="fade"),
    "memphis": dict(label="孟菲斯活力", en="Memphis Pop", preset="12 Sagmeister & Walsh",
        philosophy="高饱和撞色 + 几何形状，适合活动宣传与轻松场景。",
        bg="FFFFFF", surface="FFF7F2", ink="111111", ink2="6E6E6E", accent="FF4D6D", accent2="2EC4B6",
        line="F0D9E0", title_font=(FONT_SANS, FONT_SANS_EA), body_font=(FONT_SANS, FONT_SANS_EA),
        radius=0.14, decor="pop", decor3="FFB703", transition="wipe"),
    "glass": dict(label="玻璃拟态", en="Glassmorphism", preset="05 Locomotive",
        philosophy="深色渐变 + 半透明卡片，适合产品发布与科技展示。",
        bg="101826", surface="1B2A44", ink="F2F6FF", ink2="9FB2D0", accent="7CC4FF", accent2="A78BFA",
        line="33456B", title_font=(FONT_SANS, FONT_SANS_EA), body_font=(FONT_SANS, FONT_SANS_EA),
        radius=0.12, decor="glass", transition="morph"),
    "terminal": dict(label="赛博终端", en="Cyber Terminal", preset="08 Resn",
        philosophy="黑底绿字等宽，命令行气质，适合技术教学与极客分享。",
        bg="0A0E0A", surface="111711", ink="C8FACC", ink2="6F9E78", accent="38D39F", accent2="E2E23F",
        line="1E2A1E", title_font=(FONT_MONO, FONT_MONO_EA), body_font=(FONT_MONO, FONT_MONO_EA),
        radius=0.0, decor="term", transition="push"),
    "organic": dict(label="自然有机", en="Organic", preset="18 Kenya Hara",
        philosophy="暖砂底 + 植物绿/陶土色，柔和圆角，适合笔记与生活方式主题。",
        bg="F3EFE6", surface="FFFFFF", ink="33352E", ink2="8C8A78", accent="6B8E5A", accent2="C98A5E",
        line="E3DCCB", title_font=(FONT_SANS, FONT_SANS_EA), body_font=(FONT_SANS, FONT_SANS_EA),
        radius=0.22, decor="organic", transition="fade"),
    "academic": dict(label="学术严谨", en="Academic", preset="04 Fathom",
        philosophy="冷静灰蓝 + 严谨结构，适合研究、课件与数据报告。",
        bg="FFFFFF", surface="F4F6F8", ink="22252A", ink2="6B7280", accent="34508C", accent2="B4552D",
        line="DDE3EA", title_font=(FONT_SERIF, FONT_SERIF_EA), body_font=(FONT_SANS, FONT_SANS_EA),
        radius=0.03, decor="rule", transition="fade"),
    "monochrome": dict(label="单色印刷极简", en="Monochrome", preset="03 Information Architects",
        philosophy="黑白灰三阶，靠字号与留白分级，极致克制。",
        bg="FFFFFF", surface="F4F4F4", ink="0A0A0A", ink2="8C8C8C", accent="0A0A0A", accent2="3D3D3D",
        line="E0E0E0", title_font=(FONT_SANS, FONT_SANS_EA), body_font=(FONT_SANS, FONT_SANS_EA),
        radius=0.0, decor="rule", transition="fade"),
    "blueprint": dict(label="工程蓝图", en="Blueprint", preset="14 Raven Kwok",
        philosophy="深蓝底 + 白色线稿与网格，工程/架构语境。",
        bg="0E2A47", surface="123456", ink="EAF3FF", ink2="8FB3D9", accent="6FD3FF", accent2="FFD166",
        line="1E4470", title_font=(FONT_MONO, FONT_MONO_EA), body_font=(FONT_SANS, FONT_SANS_EA),
        radius=0.0, decor="grid", transition="push"),
    "pastel": dict(label="马卡龙柔彩", en="Pastel", preset="17 Takram",
        philosophy="低饱和柔彩 + 圆角，轻盈亲和，适合教学与生活主题。",
        bg="FDF7F9", surface="FFFFFF", ink="3A3A44", ink2="9B94A8", accent="F49AC1", accent2="8FD3C7",
        line="F0E3EA", title_font=(FONT_SANS, FONT_SANS_EA), body_font=(FONT_SANS, FONT_SANS_EA),
        radius=0.26, decor="soft", transition="fade"),
    "luxury": dict(label="轻奢金黑", en="Luxury Noir", preset="11 Build",
        philosophy="近黑底 + 香槟金细线，高端质感，适合品牌与高端方案。",
        bg="14120F", surface="1E1B16", ink="F5EFE3", ink2="A79B84", accent="C9A227", accent2="E8D9B5",
        line="2E2A22", title_font=(FONT_SERIF, FONT_SERIF_EA), body_font=(FONT_SANS, FONT_SANS_EA),
        radius=0.04, decor="rule", transition="morph"),
    "vaporwave": dict(label="蒸汽波", en="Vaporwave", preset="06 Active Theory",
        philosophy="紫粉青渐变 + 霓虹，复古未来感，适合潮流与娱乐主题。",
        bg="1A1036", surface="241548", ink="F6E9FF", ink2="B49CE0", accent="FF5FD2", accent2="37E6D0",
        line="3A2A66", title_font=(FONT_SANS, FONT_SANS_EA), body_font=(FONT_SANS, FONT_SANS_EA),
        radius=0.10, decor="glow", transition="morph"),
    "risograph": dict(label="孔版双色", en="Risograph", preset="19 Irma Boom",
        philosophy="双色错版叠加，纸张质感，适合作品集与独立出版。",
        bg="F7F3EC", surface="FFFFFF", ink="20242C", ink2="7C7A72", accent="FF4A5E", accent2="2A6BE2",
        line="E7DFD2", title_font=(FONT_SANS, FONT_SANS_EA), body_font=(FONT_SANS, FONT_SANS_EA),
        radius=0.0, decor="pop", decor3="FFC93C", transition="fade"),
    "bauhaus": dict(label="包豪斯三原色", en="Bauhaus", preset="09 Experimental Jetset",
        philosophy="红黄蓝 + 黑白，几何构成，强形式感。",
        bg="F4F1EA", surface="FFFFFF", ink="111111", ink2="6B6B6B", accent="E2231A", accent2="1F49C4",
        line="DCD8CE", title_font=(FONT_SANS, FONT_SANS_EA), body_font=(FONT_SANS, FONT_SANS_EA),
        radius=0.0, decor="pop", decor3="F5C518", transition="wipe"),
    "nordic": dict(label="北欧灰蓝", en="Nordic", preset="03 Information Architects",
        philosophy="冷灰蓝 + 米白，安静克制，适合调研与说明类内容。",
        bg="F7F8FA", surface="FFFFFF", ink="22303C", ink2="7C8A99", accent="4C7CA8", accent2="C2857A",
        line="E2E7EC", title_font=(FONT_SANS, FONT_SANS_EA), body_font=(FONT_SANS, FONT_SANS_EA),
        radius=0.08, decor="rule", transition="fade"),
    "isometric": dict(label="等距信息图", en="Isometric", preset="02 Stamen Design",
        philosophy="等距网格与块状图形，信息图像化，适合流程与结构说明。",
        bg="F2F5F3", surface="FFFFFF", ink="1E2A26", ink2="7F8C87", accent="1FA97A", accent2="F2994A",
        line="DDE6E1", title_font=(FONT_SANS, FONT_SANS_EA), body_font=(FONT_SANS, FONT_SANS_EA),
        radius=0.10, decor="soft", transition="push"),
    "gradient": dict(label="渐变流体", en="Gradient Flow", preset="07 Field.io",
        philosophy="柔和渐变与流形色块，现代产品感，适合发布与介绍。",
        bg="141A2E", surface="1E2740", ink="EEF2FF", ink2="9AA7CC", accent="6C8CFF", accent2="FF8FB1",
        line="2A3556", title_font=(FONT_SANS, FONT_SANS_EA), body_font=(FONT_SANS, FONT_SANS_EA),
        radius=0.18, decor="glass", transition="morph"),
    "newspaper": dict(label="报纸排版", en="Newspaper", preset="01 Pentagram",
        philosophy="多栏密排 + 衬线标题 + 细规线，信息密度高，适合综述与年鉴。",
        bg="FBF9F4", surface="FFFFFF", ink="16130E", ink2="6E675B", accent="8C1D18", accent2="2A2A28",
        line="DDD6C8", title_font=(FONT_SERIF, FONT_SERIF_EA), body_font=(FONT_SERIF, FONT_SERIF_EA),
        radius=0.0, decor="rule", transition="fade"),
    "chalk": dict(label="黑板粉笔", en="Chalkboard", preset="15 Ash Thorp",
        philosophy="深墨绿黑板 + 粉笔白黄，课堂气质，适合教学与讲解。",
        bg="1E2A26", surface="26332E", ink="F1F3EE", ink2="A9B6AE", accent="F5D67B", accent2="8FD3C7",
        line="33423B", title_font=(FONT_MONO, FONT_MONO_EA), body_font=(FONT_SANS, FONT_SANS_EA),
        radius=0.06, decor="organic", transition="fade"),
}

# 24 个用途分类（用途更多样）
_CATS = [
    ("01-teaching", "编程教学课件", "Programming Courseware", "课程讲授、培训讲义、知识点串讲、课堂演示", ["呼吸留白极简", "赛博终端", "柔和科技图表", "黑板粉笔", "学术严谨"]),
    ("02-game-gdd", "游戏设计提案", "Game Design Proposal", "游戏设计文档、玩法提案、立项与评审", ["暗黑霓虹", "复古像素", "商务蓝调", "等距信息图", "蒸汽波"]),
    ("03-portfolio", "像素与美术作品集", "Pixel & Art Portfolio", "作品集展示、约稿投稿、个人介绍", ["杂志编辑", "复古像素", "呼吸留白极简", "孔版双色", "轻奢金黑"]),
    ("04-club-event", "社团活动策划", "Club Event Planning", "活动策划、社团申报、竞聘述职、招新宣讲", ["孟菲斯活力", "自然有机", "呼吸留白极简", "马卡龙柔彩", "包豪斯三原色"]),
    ("05-project-report", "项目汇报与复盘", "Project Report & Retrospective", "项目汇报、结项答辩、复盘总结", ["数学网格功能主义", "商务蓝调", "呼吸留白极简", "北欧灰蓝", "学术严谨"]),
    ("06-study-notes", "学习笔记分享", "Study Notes Sharing", "学习笔记分享、读书会、知识科普", ["柔和科技图表", "自然有机", "杂志编辑", "学术严谨", "单色印刷极简"]),
    ("07-resume", "求职简历与自我介绍", "Resume & Self-Intro", "求职简历、自我介绍、面试展示", ["呼吸留白极简", "杂志编辑", "北欧灰蓝", "单色印刷极简", "轻奢金黑"]),
    ("08-promo", "活动宣传与推广", "Event Promo", "活动宣传、招新推广、作品发布", ["孟菲斯活力", "玻璃拟态", "暗黑霓虹", "包豪斯三原色", "马卡龙柔彩"]),
    ("09-dashboard", "数据看板与指标", "Data Dashboard", "数据看板、指标汇报、季度数据展示", ["商务蓝调", "玻璃拟态", "柔和科技图表", "渐变流体", "等距信息图"]),
    ("10-creative-pitch", "内容创作提案", "Creative Pitch", "动画 / 剧本 / 视频等创作提案", ["杂志编辑", "暗黑霓虹", "自然有机", "报纸排版", "蒸汽波"]),
    ("11-product-launch", "产品发布与介绍", "Product Launch", "作品/工具发布、版本更新说明", ["渐变流体", "玻璃拟态", "轻奢金黑", "呼吸留白极简", "暗黑霓虹"]),
    ("12-reading-club", "读书会与共读分享", "Reading Club", "读书笔记、共读导读", ["杂志编辑", "自然有机", "报纸排版", "马卡龙柔彩", "单色印刷极简"]),
    ("13-job-competition", "竞聘述职与答辩", "Job Competition", "社团竞聘、岗位述职", ["商务蓝调", "呼吸留白极简", "数学网格功能主义", "学术严谨", "北欧灰蓝"]),
    ("14-contest-defense", "比赛答辩与路演", "Contest Defense", "学科/创业比赛答辩", ["数学网格功能主义", "渐变流体", "商务蓝调", "暗黑霓虹", "工程蓝图"]),
    ("15-course-syllabus", "课程大纲与教学计划", "Course Syllabus", "课程设计、教学安排", ["学术严谨", "柔和科技图表", "北欧灰蓝", "黑板粉笔", "等距信息图"]),
    ("16-recruitment", "招新宣讲与纳新", "Recruitment", "社团招新、部门纳新", ["孟菲斯活力", "马卡龙柔彩", "包豪斯三原色", "玻璃拟态", "蒸汽波"]),
    ("17-annual-review", "年度总结与规划", "Annual Review", "个人/组织年度总结", ["报纸排版", "杂志编辑", "商务蓝调", "单色印刷极简", "渐变流体"]),
    ("18-training-manual", "培训手册与 SOP", "Training Manual", "流程规范、新人培训", ["单色印刷极简", "北欧灰蓝", "学术严谨", "等距信息图", "黑板粉笔"]),
    ("19-user-research", "用户调研与访谈", "User Research", "问卷结果、访谈纪要", ["柔和科技图表", "北欧灰蓝", "学术严谨", "自然有机", "单色印刷极简"]),
    ("20-market-analysis", "市场与竞品分析", "Market Analysis", "竞品对比、市场机会", ["商务蓝调", "数学网格功能主义", "渐变流体", "报纸排版", "玻璃拟态"]),
    ("21-budget-plan", "预算与财务计划", "Budget & Finance", "经费预算、成本计划", ["数学网格功能主义", "商务蓝调", "等距信息图", "单色印刷极简", "北欧灰蓝"]),
    ("22-travel-plan", "旅行与行程计划", "Travel Plan", "行程规划、攻略分享", ["自然有机", "马卡龙柔彩", "杂志编辑", "孔版双色", "蒸汽波"]),
    ("23-open-source-release", "开源项目发布", "Open Source Release", "版本发布、贡献指南", ["赛博终端", "工程蓝图", "暗黑霓虹", "单色印刷极简", "渐变流体"]),
    ("24-tech-review", "技术架构评审", "Tech Architecture Review", "架构设计、技术选型评审", ["工程蓝图", "等距信息图", "数学网格功能主义", "赛博终端", "单色印刷极简"]),
]

LABEL2KEY = {v["label"]: k for k, v in THEMES.items()}
CATEGORIES = [dict(id=i, name=n, en=e, needs=nd, styles=[LABEL2KEY.get(x, x) for x in s]) for (i, n, e, nd, s) in _CATS]
